#pragma once
// I WILL USE THIS ENUM CLASS IN FUTURE IF I WANT TO EXPAND THE CODE
// FOR NOW THIS CLASS IS NOT THAT MUCH NECESSARY BUT WILL STILL USE IT :)
// SINCE SCHOOL TIMINGS ARE FIXED SO MADE AN ENUM CLASS FOR A SMOOTH CODE
enum class TimeSlot {
    Default,
    Morning,
    Afternoon,
    Evening
};
